# Generated by Django 5.2.7 on 2025-10-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('crm', models.CharField(blank=True, max_length=30)),
                ('specialty', models.CharField(choices=[('Clínica Médica', 'Clínica Médica'), ('Pediatria', 'Pediatria'), ('Ginecologia', 'Ginecologia'), ('Ortopedia', 'Ortopedia'), ('Cardiologia', 'Cardiologia')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Concluída'), ('no_show', 'Não compareceu'), ('cancelled', 'Cancelada')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment')),
                ('diagnoses', models.ManyToManyField(blank=True, to='clinic.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.encounter')),
            ],
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at', 'status'], name='clinic_appo_schedul_feafb1_idx'),
        ),
    ]
