# Generated by Django 5.2.7 on 2025-10-09 20:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_estimate_min', models.PositiveSmallIntegerField(default=20)),
                ('requires_image_guidance', models.BooleanField(default=False)),
                ('price_brl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='clinic.procedure'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.procedurecategory'),
        ),
    ]
