# Generated by Django 5.2.7 on 2025-10-14 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_procedure_procedurecategory_encounter_procedures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=120)),
                ('protocol', models.CharField(choices=[('LASER', 'Laser de Alta Potência / Laserterapia'), ('INFIL', 'Infiltrações Articulares/Musculares'), ('BLOCK', 'Bloqueios Simpáticos / Neuroaxiais'), ('RF', 'Radiofrequência Convencional/Pulsada'), ('ESWT', 'Ondas de Choque Extracorpóreas (ESWT)')], max_length=10)),
                ('start_date', models.DateField()),
                ('goal_pain_score', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CareStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateField()),
                ('done_at', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='clinic.careplan')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_steps', to='clinic.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='PainAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_assessments', to='clinic.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_assessments', to='clinic.patient')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
